Repository Brexbot/TwiggyBot, pull requests merged in 2022-04, with the labels that each got.

#116 Pardon Timeout + Mod Timeout Bypass
  src/commands/modCommands/Pardon.ts
  src/commands/timeout.ts
  src/guards/RoleChecks.ts
Labels: bug, enhancement

#119 Add minesweeper command
  src/commands/minesweeper.ts
Labels: enhancement

#120 Handle a failed respose when fetching quote data
  src/commands/quote.ts
Labels: bug
